# -*- coding: utf-8 -*-
"""predictor_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWOUglJ68nZ2xiywzZ3-t9L4M2uozlIq
"""

<<<<<<< HEAD
# predictor_app.py (Versão Final Otimizada)

=======
# predictor_app.py
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3
import streamlit as st
import pandas as pd
import joblib
import shap
import matplotlib.pyplot as plt

# =============================================================================
<<<<<<< HEAD
# Carregamento dos Artefatos (Apenas o necessário para a UI iniciar)
# =============================================================================
st.set_page_config(layout="wide", page_title="Analisador de Fraude")

# Usar o cache do Streamlit para carregar os modelos apenas uma vez
@st.cache_resource
def load_artifacts():
    try:
        model = joblib.load('model_xgboost.joblib')
        scaler = joblib.load('scaler.joblib')
        features_modelo = joblib.load('features_modelo.joblib')
        ui_features_info = joblib.load('ui_features_info.joblib')
        return model, scaler, features_modelo, ui_features_info
    except FileNotFoundError:
        return None, None, None, None

model, scaler, features_modelo, ui_features_info = load_artifacts()

if model is None:
    st.error("ERRO: Arquivos de modelo, scaler ou features não encontrados. Certifique-se de que eles foram enviados para o seu repositório GitHub e reinicie o aplicativo.")
    st.stop()

# =============================================================================
# Interface do Usuário (UI) com Streamlit
# =============================================================================
=======
# Carregamento dos Artefatos (Modelo, Scaler, Features)
# =============================================================================
try:
    model = joblib.load('/content/drive/MyDrive/Projetos/Detecão Fraude/model_xgboost.joblib')
    scaler = joblib.load('/content/drive/MyDrive/Projetos/Detecão Fraude/scaler.joblib')
    features_modelo = joblib.load('/content/drive/MyDrive/Projetos/Detecão Fraude/features_modelo.joblib')
    ui_features_info = joblib.load('/content/drive/MyDrive/Projetos/Detecão Fraude/ui_features_info.joblib')
except FileNotFoundError:
    st.error("Arquivos de modelo, scaler ou features não encontrados. Por favor, execute o 'final_training_script.py' primeiro.")
    st.stop()

# Criar o explainer do SHAP (fazemos isso uma vez para otimizar)
explainer = shap.TreeExplainer(model)

# =============================================================================
# Interface do Usuário (UI) com Streamlit
# =============================================================================
st.set_page_config(layout="wide", page_title="Analisador de Fraude")
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3
st.title("Analisador de Fraude em Transações Financeiras 🤖")
st.write("Esta ferramenta utiliza um modelo de Machine Learning (XGBoost) para prever a probabilidade de uma transação ser fraudulenta. Insira os dados da transação na barra lateral para obter uma análise em tempo real.")

# --- Barra Lateral para Inserção de Dados ---
st.sidebar.header("Dados da Nova Transação")

# Dicionário para armazenar os inputs do usuário
user_inputs = {}

# Inputs para Time e Amount
user_inputs['Time'] = st.sidebar.number_input(
    'Tempo (em segundos desde a primeira transação)',
    min_value=float(ui_features_info['Time']['min']),
    max_value=float(ui_features_info['Time']['max']),
<<<<<<< HEAD
    value=float(ui_features_info['Time']['min'])
=======
    value=float(ui_features_info['Time']['min']) # Valor padrão
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3
)
user_inputs['Amount'] = st.sidebar.number_input(
    'Valor da Transação (Amount)',
    min_value=float(ui_features_info['Amount']['min']),
<<<<<<< HEAD
    value=100.0,
=======
    value=100.0, # Valor padrão
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3
    format="%.2f"
)

# Inputs para as features V1-V28 usando sliders
st.sidebar.subheader("Features Anônimas (V1-V28)")
for feature in features_modelo:
    if feature.startswith('V'):
        info = ui_features_info[feature]
        user_inputs[feature] = st.sidebar.slider(
            feature,
            min_value=float(info['min']),
            max_value=float(info['max']),
<<<<<<< HEAD
            value=0.0
=======
            value=0.0 # Valor padrão no meio
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3
        )

# Botão para realizar a predição
if st.sidebar.button("Analisar Transação"):
<<<<<<< HEAD

    # --- Processamento e Predição ---
    input_df = pd.DataFrame([user_inputs])
    input_df[['Amount_Scaled', 'Time_Scaled']] = scaler.transform(input_df[['Amount', 'Time']])
    input_df_modelo = input_df[features_modelo]
    prediction_proba = model.predict_proba(input_df_modelo)[0]
    prob_fraude = prediction_proba[1]
=======
    # --- Processamento e Predição ---
    # 1. Criar DataFrame com os dados do usuário
    input_df = pd.DataFrame([user_inputs])

    # 2. Escalar 'Time' e 'Amount' com o scaler carregado
    input_df[['Amount_Scaled', 'Time_Scaled']] = scaler.transform(input_df[['Amount', 'Time']])

    # 3. Garantir a ordem correta das colunas
    input_df_modelo = input_df[features_modelo]

    # 4. Fazer a predição de probabilidade
    prediction_proba = model.predict_proba(input_df_modelo)[0]
    prob_fraude = prediction_proba[1] # Probabilidade da classe 1 (fraude)
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3

    # --- Exibição dos Resultados ---
    st.header("Resultado da Análise")

    col1, col2 = st.columns(2)
<<<<<<< HEAD
=======

>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3
    with col1:
        if prob_fraude > 0.5: # Limiar de decisão
            st.error("ALERTA: Transação Classificada como FRAUDE!")
        else:
            st.success("Transação Classificada como NORMAL.")

    with col2:
        st.metric(label="Probabilidade de ser Fraude", value=f"{prob_fraude:.2%}")

    # --- Explicação com SHAP ---
    st.header("Justificativa da Previsão (Análise SHAP)")
    st.write("Este gráfico mostra quais fatores mais contribuíram para a decisão do modelo. Fatores em vermelho aumentam a chance de fraude, enquanto fatores em azul diminuem.")

<<<<<<< HEAD
    # A tarefa pesada agora acontece SÓ DEPOIS do clique
    with st.spinner('Gerando análise de interpretabilidade...'):
        # 1. Criar o explainer do SHAP
        explainer = shap.TreeExplainer(model)

        # 2. Calcular os valores SHAP para a única instância
        shap_values = explainer.shap_values(input_df_modelo)

        # 3. Gerar o gráfico de forças
        fig, ax = plt.subplots(figsize=(10, 3))
        shap.force_plot(
            explainer.expected_value,
            shap_values[0,:],
            input_df_modelo.iloc[0,:],
            matplotlib=True,
            show=False,
            text_rotation=15
        )
        st.pyplot(fig, bbox_inches='tight', use_container_width=True)
        st.info("O **'base value'** é a probabilidade média de fraude que o modelo aprendeu com os dados. As setas mostram como cada feature da transação atual 'empurra' essa probabilidade para o valor final da previsão **('output value')**.")
=======
    # Calcular SHAP values para a única instância
    shap_values = explainer.shap_values(input_df_modelo)

    # Gerar o gráfico de forças
    fig, ax = plt.subplots()
    shap.force_plot(
        explainer.expected_value,
        shap_values[0,:],
        input_df_modelo.iloc[0,:],
        matplotlib=True,
        show=False,
        text_rotation=15
    )
    st.pyplot(fig, bbox_inches='tight')
    st.info("O **'base value'** é a probabilidade média de fraude em todo o dataset. As setas mostram como cada feature da transação atual empurra essa probabilidade para o valor final da previsão **('output value')**.")
>>>>>>> cd196539251882b0ed11d6851800dc121380b8b3

else:
    st.info("Por favor, insira os dados da transação na barra lateral e clique em 'Analisar Transação'.")